### ISSUE TITLE
[Fix] [0.3a1] grammar and spelling errors

### ISSUE THREAD

**Issue by rkemot** [the-zphr/Better-Rivals-Text#9]
## Spelling error(s)
`07B718D6` "break"
`F3D39000` "gives you access to"
`F9BB796F` "Hit {0:s} with a Stun Mine confirmed"
`FD1AAC6F` "Stun mine hit by {0:s} 
`E56D1394` "like moron" and "didnt see Heli"

## Your solution
for `07B718D6` "brake"
for `F3D39000` "lets you"
for `F9BB796F` "Stun Mine hit confirmed on {0:s}"
for `FD1AAC6F` "{0:s} hit you with a Stun Mine"
for `E56D1394` "like a moron" and "didnt see the Heli"

## Reasoning
`07B718D6`: grammar
`F3D39000`: just better. reading "gives you access to spam that" gives me a stroke (and others probably too)
`F9BB796F`: same as above, also it seems like a general spelling mistake too
`FD1AAC6F`: stroke.
`E56D1394`: grammar again

## Additional comments
gonna update/upload more soon

**Comment by the-zphr** [comment]
Changes were approved and implemented. Fixed in 0.3a2
